steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/ai-corp-agent/ai-agent:$SHORT_SHA', '.']

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/ai-corp-agent/ai-agent:$SHORT_SHA']

  # Fetch GKE credentials
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'clusters', 'get-credentials', 'llmcorp-cluster-westus-4', '--zone', 'us-west4-a']

 # Use Alpine image to perform envsubst
  - name: 'alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        apk add --update gettext
        envsubst < kubernetes/deployment.yaml.template > kubernetes/deployment.yaml
    env:
      - 'SHORT_SHA=$SHORT_SHA'

  # Apply the Kubernetes deployment configurations
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'kubernetes/deployment.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-west4-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=llmcorp-cluster-westus-4'

  # Apply the Kubernetes service configurations
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'kubernetes/service.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-west4-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=llmcorp-cluster-westus-4'

images:
  - 'gcr.io/ai-corp-agent/ai-agent:$SHORT_SHA'
