steps:
  # Fetch GKE credentials
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'clusters', 'get-credentials', 'llmcorp-cluster-westus-4', '--zone', 'us-west4-a']

  # Check for the existence of the deployment and update if it exists
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if kubectl get deployment ai-agent-deployment; then
          kubectl set image deployment/ai-agent-deployment ai-agent=gcr.io/ai-corp-agent/ai-agent:$SHORT_SHA
        else
          echo "Deployment not found, skipping image update."
        fi

  # Apply the Kubernetes configurations
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'kubernetes/']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-west4-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=llmcorp-cluster-westus-4'

images:
  - 'gcr.io/ai-corp-agent/ai-agent:b4a15c0'
